export * from './homeHero'
export * from './homeCollection'
export * from './homebottomCarousel'
export * from './hometopCarousel'
export * from './winHome'
export * from "./whyPasaHome"
export * from "./highTideHome"
export * from "./bottomHeading"
export * from "./bottomSubHeading"
export * from "./bottomSubHeading2"
export * from "./testimonialCarousel"
export * from "./middleHeading"